# -*- coding: utf-8 -*-
"""adam_asmaca_oyun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199ZiCysBhoGq83QfKefCJO0ZMhHy5PkJ
"""

import random

kelimeler = ['elma', 'armut', 'muz', 'çilek', 'karpuz', 'kiraz', 'portakal', 'üzüm']
kelime = random.choice(kelimeler)
tahmin_edilen = ['_'] * len(kelime)
hak = 6
harfler = set()

while hak > 0 and '_' in tahmin_edilen:
    print(' '.join(tahmin_edilen))
    print(f'Kalan hak: {hak}')
    tahmin = input('Bir harf tahmin et: ').lower()
    if not tahmin or tahmin in harfler or len(tahmin) != 1 or not tahmin.isalpha():
        continue
    harfler.add(tahmin)
    if tahmin in kelime:
        for i, harf in enumerate(kelime):
            if harf == tahmin:
                tahmin_edilen[i] = tahmin
    else:
        hak -= 1

if '_' not in tahmin_edilen:
    print(f'Tebrikler! Kelimeyi bildiniz: {kelime}')
else:
    print(f'Kaybettiniz! Doğru kelime: {kelime}')